version: "3"
services:
  hourly-notification-app:
    image: hourly-notif:6
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NOTIFY_TOPIC: ${NOTIFY_TOPIC}
      NOTIFY_INTERVAL: ${NOTIFY_INTERVAL}
