version: "3"
services:
  hourly-notification-app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    environment:
      NOTIFY_TOPIC: ${NOTIFY_TOPIC}
      NOTIFY_INTERVAL: ${NOTIFY_INTERVAL}
